# nacos used in @vivycloud/config-nacos
nacos:
  # 配置管理
  config:
    client:
      serverAddr: 127.0.0.1:8848
      namespace: 455e0d52-7c0b-4df5-a9c6-51bee0885086
    configs:
      dataId: vivy-system.yaml
      group: DEFAULT_GROUP
    sharedConfigs:
      dataId: vivy-development.yaml
      group: DEFAULT_GROUP
  # 服务管理
  naming:
    client:
      serverList: 127.0.0.1:8848
      namespace: 455e0d52-7c0b-4df5-a9c6-51bee0885086
    instance:
      port: ${{ application.port }}
      serviceName: ${{ application.name }}
      metadata:
